// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategory(ctx context.Context, categoryName string) (Category, error)
	CreateGood(ctx context.Context, arg CreateGoodParams) (Good, error)
	CreateUnit(ctx context.Context, unitName string) (Unit, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteGood(ctx context.Context, id int64) error
	DeleteUnit(ctx context.Context, id int64) error
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetGood(ctx context.Context, id int64) (Good, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListGoods(ctx context.Context, arg ListGoodsParams) ([]Good, error)
	ListUnits(ctx context.Context, arg ListUnitsParams) ([]Unit, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateGood(ctx context.Context, arg UpdateGoodParams) (Good, error)
	UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error)
}

var _ Querier = (*Queries)(nil)
